#################
# Generate instances as used by Muter.2015 and described by Hwang.2005.
# All random numbers, including locations, are generated by uniform distribution.
#################
import numpy as np

cap = 48
numInstances = 100
numOrdersInInstance = 20
lowB = 2
highB = 10
d = open("Hwang-uniform-cap" + str(cap) + "-" + str(numOrdersInInstance) + "-Instances.txt", "x") # generate file of filenames
for counter in range(numInstances): #number of instances

    name = "Hwang-uniform-cap"+ str(cap) +"-"+str(counter)+".txt"
    d.write(name+"\n")
    f = open(name, "x")
    for orderCounter in range(numOrdersInInstance): #number of orders

        numItems = round(np.random.uniform(low=lowB, high=highB))

        head = "Order " + str(orderCounter) + " number of articles " + str(numItems) + "\n"
        f.write(head)
        for i in range(numItems):
            cell = round(np.random.uniform(low=0, high=44))
            aisle = round(np.random.uniform(low=0, high=19))
            line = str(i)+"	Aisle " + str(aisle) + "	Location " + str(cell) + "\n"
            print(cell, aisle)
            f.write(line)
    f.close()
d.close()



